/*
Copyright 2019 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/projectriff/bindings/pkg/apis/bindings/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSpringBootContainers implements SpringBootContainerInterface
type FakeSpringBootContainers struct {
	Fake *FakeBindingsV1alpha1
	ns   string
}

var springbootcontainersResource = schema.GroupVersionResource{Group: "bindings.projectriff.io", Version: "v1alpha1", Resource: "springbootcontainers"}

var springbootcontainersKind = schema.GroupVersionKind{Group: "bindings.projectriff.io", Version: "v1alpha1", Kind: "SpringBootContainer"}

// Get takes name of the springBootContainer, and returns the corresponding springBootContainer object, and an error if there is any.
func (c *FakeSpringBootContainers) Get(name string, options v1.GetOptions) (result *v1alpha1.SpringBootContainer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(springbootcontainersResource, c.ns, name), &v1alpha1.SpringBootContainer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SpringBootContainer), err
}

// List takes label and field selectors, and returns the list of SpringBootContainers that match those selectors.
func (c *FakeSpringBootContainers) List(opts v1.ListOptions) (result *v1alpha1.SpringBootContainerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(springbootcontainersResource, springbootcontainersKind, c.ns, opts), &v1alpha1.SpringBootContainerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SpringBootContainerList{ListMeta: obj.(*v1alpha1.SpringBootContainerList).ListMeta}
	for _, item := range obj.(*v1alpha1.SpringBootContainerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested springBootContainers.
func (c *FakeSpringBootContainers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(springbootcontainersResource, c.ns, opts))

}

// Create takes the representation of a springBootContainer and creates it.  Returns the server's representation of the springBootContainer, and an error, if there is any.
func (c *FakeSpringBootContainers) Create(springBootContainer *v1alpha1.SpringBootContainer) (result *v1alpha1.SpringBootContainer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(springbootcontainersResource, c.ns, springBootContainer), &v1alpha1.SpringBootContainer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SpringBootContainer), err
}

// Update takes the representation of a springBootContainer and updates it. Returns the server's representation of the springBootContainer, and an error, if there is any.
func (c *FakeSpringBootContainers) Update(springBootContainer *v1alpha1.SpringBootContainer) (result *v1alpha1.SpringBootContainer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(springbootcontainersResource, c.ns, springBootContainer), &v1alpha1.SpringBootContainer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SpringBootContainer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSpringBootContainers) UpdateStatus(springBootContainer *v1alpha1.SpringBootContainer) (*v1alpha1.SpringBootContainer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(springbootcontainersResource, "status", c.ns, springBootContainer), &v1alpha1.SpringBootContainer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SpringBootContainer), err
}

// Delete takes name of the springBootContainer and deletes it. Returns an error if one occurs.
func (c *FakeSpringBootContainers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(springbootcontainersResource, c.ns, name), &v1alpha1.SpringBootContainer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSpringBootContainers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(springbootcontainersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SpringBootContainerList{})
	return err
}

// Patch applies the patch and returns the patched springBootContainer.
func (c *FakeSpringBootContainers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SpringBootContainer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(springbootcontainersResource, c.ns, name, pt, data, subresources...), &v1alpha1.SpringBootContainer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SpringBootContainer), err
}
