/*
Copyright 2019 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/projectriff/bindings/pkg/apis/bindings/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBindableServices implements BindableServiceInterface
type FakeBindableServices struct {
	Fake *FakeBindingsV1alpha1
	ns   string
}

var bindableservicesResource = schema.GroupVersionResource{Group: "bindings.projectriff.io", Version: "v1alpha1", Resource: "bindableservices"}

var bindableservicesKind = schema.GroupVersionKind{Group: "bindings.projectriff.io", Version: "v1alpha1", Kind: "BindableService"}

// Get takes name of the bindableService, and returns the corresponding bindableService object, and an error if there is any.
func (c *FakeBindableServices) Get(name string, options v1.GetOptions) (result *v1alpha1.BindableService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bindableservicesResource, c.ns, name), &v1alpha1.BindableService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BindableService), err
}

// List takes label and field selectors, and returns the list of BindableServices that match those selectors.
func (c *FakeBindableServices) List(opts v1.ListOptions) (result *v1alpha1.BindableServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bindableservicesResource, bindableservicesKind, c.ns, opts), &v1alpha1.BindableServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BindableServiceList{ListMeta: obj.(*v1alpha1.BindableServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.BindableServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bindableServices.
func (c *FakeBindableServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bindableservicesResource, c.ns, opts))

}

// Create takes the representation of a bindableService and creates it.  Returns the server's representation of the bindableService, and an error, if there is any.
func (c *FakeBindableServices) Create(bindableService *v1alpha1.BindableService) (result *v1alpha1.BindableService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bindableservicesResource, c.ns, bindableService), &v1alpha1.BindableService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BindableService), err
}

// Update takes the representation of a bindableService and updates it. Returns the server's representation of the bindableService, and an error, if there is any.
func (c *FakeBindableServices) Update(bindableService *v1alpha1.BindableService) (result *v1alpha1.BindableService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bindableservicesResource, c.ns, bindableService), &v1alpha1.BindableService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BindableService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBindableServices) UpdateStatus(bindableService *v1alpha1.BindableService) (*v1alpha1.BindableService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bindableservicesResource, "status", c.ns, bindableService), &v1alpha1.BindableService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BindableService), err
}

// Delete takes name of the bindableService and deletes it. Returns an error if one occurs.
func (c *FakeBindableServices) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bindableservicesResource, c.ns, name), &v1alpha1.BindableService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBindableServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bindableservicesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.BindableServiceList{})
	return err
}

// Patch applies the patch and returns the patched bindableService.
func (c *FakeBindableServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BindableService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bindableservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.BindableService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BindableService), err
}
