/*
Copyright 2019 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/projectriff/bindings/pkg/apis/bindings/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFrogBindings implements FrogBindingInterface
type FakeFrogBindings struct {
	Fake *FakeBindingsV1alpha1
	ns   string
}

var frogbindingsResource = schema.GroupVersionResource{Group: "bindings.projectriff.io", Version: "v1alpha1", Resource: "frogbindings"}

var frogbindingsKind = schema.GroupVersionKind{Group: "bindings.projectriff.io", Version: "v1alpha1", Kind: "FrogBinding"}

// Get takes name of the frogBinding, and returns the corresponding frogBinding object, and an error if there is any.
func (c *FakeFrogBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.FrogBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(frogbindingsResource, c.ns, name), &v1alpha1.FrogBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FrogBinding), err
}

// List takes label and field selectors, and returns the list of FrogBindings that match those selectors.
func (c *FakeFrogBindings) List(opts v1.ListOptions) (result *v1alpha1.FrogBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(frogbindingsResource, frogbindingsKind, c.ns, opts), &v1alpha1.FrogBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FrogBindingList{ListMeta: obj.(*v1alpha1.FrogBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.FrogBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested frogBindings.
func (c *FakeFrogBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(frogbindingsResource, c.ns, opts))

}

// Create takes the representation of a frogBinding and creates it.  Returns the server's representation of the frogBinding, and an error, if there is any.
func (c *FakeFrogBindings) Create(frogBinding *v1alpha1.FrogBinding) (result *v1alpha1.FrogBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(frogbindingsResource, c.ns, frogBinding), &v1alpha1.FrogBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FrogBinding), err
}

// Update takes the representation of a frogBinding and updates it. Returns the server's representation of the frogBinding, and an error, if there is any.
func (c *FakeFrogBindings) Update(frogBinding *v1alpha1.FrogBinding) (result *v1alpha1.FrogBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(frogbindingsResource, c.ns, frogBinding), &v1alpha1.FrogBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FrogBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFrogBindings) UpdateStatus(frogBinding *v1alpha1.FrogBinding) (*v1alpha1.FrogBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(frogbindingsResource, "status", c.ns, frogBinding), &v1alpha1.FrogBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FrogBinding), err
}

// Delete takes name of the frogBinding and deletes it. Returns an error if one occurs.
func (c *FakeFrogBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(frogbindingsResource, c.ns, name), &v1alpha1.FrogBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFrogBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(frogbindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.FrogBindingList{})
	return err
}

// Patch applies the patch and returns the patched frogBinding.
func (c *FakeFrogBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FrogBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(frogbindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.FrogBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FrogBinding), err
}
