/*
Copyright 2019 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/projectriff/bindings/pkg/apis/bindings/v1alpha1"
	scheme "github.com/projectriff/bindings/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SpringBootContainersGetter has a method to return a SpringBootContainerInterface.
// A group's client should implement this interface.
type SpringBootContainersGetter interface {
	SpringBootContainers(namespace string) SpringBootContainerInterface
}

// SpringBootContainerInterface has methods to work with SpringBootContainer resources.
type SpringBootContainerInterface interface {
	Create(*v1alpha1.SpringBootContainer) (*v1alpha1.SpringBootContainer, error)
	Update(*v1alpha1.SpringBootContainer) (*v1alpha1.SpringBootContainer, error)
	UpdateStatus(*v1alpha1.SpringBootContainer) (*v1alpha1.SpringBootContainer, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SpringBootContainer, error)
	List(opts v1.ListOptions) (*v1alpha1.SpringBootContainerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SpringBootContainer, err error)
	SpringBootContainerExpansion
}

// springBootContainers implements SpringBootContainerInterface
type springBootContainers struct {
	client rest.Interface
	ns     string
}

// newSpringBootContainers returns a SpringBootContainers
func newSpringBootContainers(c *BindingsV1alpha1Client, namespace string) *springBootContainers {
	return &springBootContainers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the springBootContainer, and returns the corresponding springBootContainer object, and an error if there is any.
func (c *springBootContainers) Get(name string, options v1.GetOptions) (result *v1alpha1.SpringBootContainer, err error) {
	result = &v1alpha1.SpringBootContainer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("springbootcontainers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SpringBootContainers that match those selectors.
func (c *springBootContainers) List(opts v1.ListOptions) (result *v1alpha1.SpringBootContainerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SpringBootContainerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("springbootcontainers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested springBootContainers.
func (c *springBootContainers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("springbootcontainers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a springBootContainer and creates it.  Returns the server's representation of the springBootContainer, and an error, if there is any.
func (c *springBootContainers) Create(springBootContainer *v1alpha1.SpringBootContainer) (result *v1alpha1.SpringBootContainer, err error) {
	result = &v1alpha1.SpringBootContainer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("springbootcontainers").
		Body(springBootContainer).
		Do().
		Into(result)
	return
}

// Update takes the representation of a springBootContainer and updates it. Returns the server's representation of the springBootContainer, and an error, if there is any.
func (c *springBootContainers) Update(springBootContainer *v1alpha1.SpringBootContainer) (result *v1alpha1.SpringBootContainer, err error) {
	result = &v1alpha1.SpringBootContainer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("springbootcontainers").
		Name(springBootContainer.Name).
		Body(springBootContainer).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *springBootContainers) UpdateStatus(springBootContainer *v1alpha1.SpringBootContainer) (result *v1alpha1.SpringBootContainer, err error) {
	result = &v1alpha1.SpringBootContainer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("springbootcontainers").
		Name(springBootContainer.Name).
		SubResource("status").
		Body(springBootContainer).
		Do().
		Into(result)
	return
}

// Delete takes name of the springBootContainer and deletes it. Returns an error if one occurs.
func (c *springBootContainers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("springbootcontainers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *springBootContainers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("springbootcontainers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched springBootContainer.
func (c *springBootContainers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SpringBootContainer, err error) {
	result = &v1alpha1.SpringBootContainer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("springbootcontainers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
