/*
Copyright 2019 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/projectriff/bindings/pkg/apis/service/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProvisionedServices implements ProvisionedServiceInterface
type FakeProvisionedServices struct {
	Fake *FakeServiceV1alpha1
	ns   string
}

var provisionedservicesResource = schema.GroupVersionResource{Group: "service.binding", Version: "v1alpha1", Resource: "provisionedservices"}

var provisionedservicesKind = schema.GroupVersionKind{Group: "service.binding", Version: "v1alpha1", Kind: "ProvisionedService"}

// Get takes name of the provisionedService, and returns the corresponding provisionedService object, and an error if there is any.
func (c *FakeProvisionedServices) Get(name string, options v1.GetOptions) (result *v1alpha1.ProvisionedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(provisionedservicesResource, c.ns, name), &v1alpha1.ProvisionedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisionedService), err
}

// List takes label and field selectors, and returns the list of ProvisionedServices that match those selectors.
func (c *FakeProvisionedServices) List(opts v1.ListOptions) (result *v1alpha1.ProvisionedServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(provisionedservicesResource, provisionedservicesKind, c.ns, opts), &v1alpha1.ProvisionedServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProvisionedServiceList{ListMeta: obj.(*v1alpha1.ProvisionedServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProvisionedServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested provisionedServices.
func (c *FakeProvisionedServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(provisionedservicesResource, c.ns, opts))

}

// Create takes the representation of a provisionedService and creates it.  Returns the server's representation of the provisionedService, and an error, if there is any.
func (c *FakeProvisionedServices) Create(provisionedService *v1alpha1.ProvisionedService) (result *v1alpha1.ProvisionedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(provisionedservicesResource, c.ns, provisionedService), &v1alpha1.ProvisionedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisionedService), err
}

// Update takes the representation of a provisionedService and updates it. Returns the server's representation of the provisionedService, and an error, if there is any.
func (c *FakeProvisionedServices) Update(provisionedService *v1alpha1.ProvisionedService) (result *v1alpha1.ProvisionedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(provisionedservicesResource, c.ns, provisionedService), &v1alpha1.ProvisionedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisionedService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProvisionedServices) UpdateStatus(provisionedService *v1alpha1.ProvisionedService) (*v1alpha1.ProvisionedService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(provisionedservicesResource, "status", c.ns, provisionedService), &v1alpha1.ProvisionedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisionedService), err
}

// Delete takes name of the provisionedService and deletes it. Returns an error if one occurs.
func (c *FakeProvisionedServices) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(provisionedservicesResource, c.ns, name), &v1alpha1.ProvisionedService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProvisionedServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(provisionedservicesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProvisionedServiceList{})
	return err
}

// Patch applies the patch and returns the patched provisionedService.
func (c *FakeProvisionedServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ProvisionedService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(provisionedservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProvisionedService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProvisionedService), err
}
